name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Fmt
      run: cargo fmt --check

  build:
    needs: check
    runs-on: ${{ matrix.runner }}
    
    strategy:
      matrix:
        include:
        # Linux config
        - name: linux-amd64
          runner: ubuntu-latest
          target: x86_64-unknown-linux-gnu
          command: cross
        - name: linux-arm64
          runner: ubuntu-latest
          target: aarch64-unknown-linux-gnu
          command: cross
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
 
      # Only install cross if we need it
      # Install via cargo-binstall which I found faster
      - name: Install Cross
        if: matrix.command == 'cross'
        shell: bash
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall --no-confirm cross
      
      - name: Build
        run: ${{ matrix.command }} build --verbose --release --target ${{ matrix.target }}


  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo test --verbose
